### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kingchun1991** [GraphCMS/graphcms-commerce-starter#22]
just replace the .env of my own  and created a graphcms commerce starter with the demo project  

then do yarn build locally or on vercel, same error occurs:

local:
```
> Build error occurred
Error: GraphQL Error (Code: 404): {"response":{"error":"Page not found.","status":404},"request":{"query":"\n  query AllCollectionsQuery($locale: Locale!) {\n    collections(locales: [$locale, en]) {\n      ...CollectionFragment\n    }\n  }\n\n  \n  fragment CollectionFragment on Collection {\n    id\n    description\n    name\n    slug\n  }\n\n","variables":{"locale":"en"}}}
    at GraphQLClient.<anonymous> (/Users/kingchuno/Desktop/git/bsg-ecommerce/node_modules/graphql-request/dist/index.js:170:35)
    at step (/Users/kingchuno/Desktop/git/bsg-ecommerce/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/kingchuno/Desktop/git/bsg-ecommerce/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/Users/kingchuno/Desktop/git/bsg-ecommerce/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'ClientError',
  response: { error: 'Page not found.', status: 404 },
  request: {
    query: '\n' +
      '  query AllCollectionsQuery($locale: Locale!) {\n' +
      '    collections(locales: [$locale, en]) {\n' +
      '      ...CollectionFragment\n' +
      '    }\n' +
      '  }\n' +
      '\n' +
      '  \n' +
      '  fragment CollectionFragment on Collection {\n' +
      '    id\n' +
      '    description\n' +
      '    name\n' +
      '    slug\n' +
      '  }\n' +
      '\n',
    variables: { locale: 'en' }
  }
}
error Command failed with exit code 1.
```

vercel

`

18:57:30 | yarn install v1.22.10
-- | --
18:57:30 | [1/4] Resolving packages...
18:57:30 | [2/4] Fetching packages...
18:57:38 | info fsevents@2.1.3: The platform "linux" is incompatible with this module.
18:57:38 | info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
18:57:38 | info fsevents@2.3.1: The platform "linux" is incompatible with this module.
18:57:38 | info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
18:57:38 | info fsevents@1.2.13: The platform "linux" is incompatible with this module.
18:57:38 | info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
18:57:38 | [3/4] Linking dependencies...
18:57:43 | [4/4] Building fresh packages...
18:57:44 | Done in 14.60s.
18:57:45 | Detected Next.js version: 10.0.5
18:57:45 | Running "yarn run build"
18:57:45 | yarn run v1.22.10
18:57:45 | $ next build
18:57:45 | Browserslist: caniuse-lite is outdated. Please run:
18:57:45 | npx browserslist@latest --update-db
18:57:46 | info  - Creating an optimized production build...
18:57:46 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
18:57:46 | This information is used to shape Next.js' roadmap and prioritize features.
18:57:46 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
18:57:46 | https://nextjs.org/telemetry
18:58:01 | info  - Compiled successfully
18:58:01 | info  - Collecting page data...
18:58:01 | > Build error occurred
18:58:01 | Error: GraphQL Error (Code: 404): {"response":{"error":"Page not found.","status":404},"request":{"query":"\n  query AllCategoriesQuery($locale: Locale!) {\n    categories(locales: [$locale, en]) {\n      ...CategoryFragment\n    }\n  }\n\n  \n  fragment CategoryFragment on Category {\n    id\n    description\n    name\n    slug\n  }\n\n","variables":{"locale":"en"}}}
18:58:01 | at GraphQLClient.<anonymous> (/vercel/path0/node_modules/graphql-request/dist/index.js:170:35)
18:58:01 | at step (/vercel/path0/node_modules/graphql-request/dist/index.js:63:23)
18:58:01 | at Object.next (/vercel/path0/node_modules/graphql-request/dist/index.js:44:53)
18:58:01 | at fulfilled (/vercel/path0/node_modules/graphql-request/dist/index.js:35:58)
18:58:01 | at processTicksAndRejections (internal/process/task_queues.js:93:5) {
18:58:01 | type: 'ClientError',
18:58:01 | response: { error: 'Page not found.', status: 404 },
18:58:01 | request: {
18:58:01 | query: '\n' +
18:58:01 | '  query AllCategoriesQuery($locale: Locale!) {\n' +
18:58:01 | '    categories(locales: [$locale, en]) {\n' +
18:58:01 | '      ...CategoryFragment\n' +
18:58:01 | '    }\n' +
18:58:01 | '  }\n' +
18:58:01 | '\n' +
18:58:01 | '  \n' +
18:58:01 | '  fragment CategoryFragment on Category {\n' +
18:58:01 | '    id\n' +
18:58:01 | '    description\n' +
18:58:01 | '    name\n' +
18:58:01 | '    slug\n' +
18:58:01 | '  }\n' +
18:58:01 | '\n',
18:58:01 | variables: { locale: 'en' }
18:58:01 | }
18:58:01 | }
18:58:01 | error Command failed with exit code 1.
18:58:01 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:58:01 | Error: Command "yarn run build" exited with 1

`

**Comment by kingchun1991** [comment]
fixed token issue
